### ISSUE TITLE
Configurate alpha-pooling for ResNet ?

### ISSUE THREAD

**Issue by hiyijian** [cvjena/alpha_pooling#1]
Dear @cvjena,
   I am trying to replace average pooing with alpha-pooling of ResNet. I plan to use this modified ResNet to train ImageNet-1000. I notice that your modified VGG-16 has some "SpatialTransformer" stuff, which is out of my best knowledge. Here is my question:
  * Is it necessary  to use "SpatialTransformer" and "alpha-pooling"  at the same time?
  * alpha-pooling = SignedPower + CompactBilinear ? or alpha-pooling = SignedPower + CompactBilinear + SignedPower?
 
I am really appreciated if you have other guide

Thanks

**Comment by MarcelSimon** [comment]
Hi and thanks for your interest in the work.
The spatial transformer layer is only used to resize the input images during multi scale training. You can omit it by either training only single scale or by implementing resizing by other operations like average pooling layer. 
For your second question: CompactBilinear has two inputs. The first one is the output of signed power and the second one is the unmodified feature. The output of CompactBilinear is passed to another signed power layer to calculate the signed square root as in previous work. The exponent is not learned but fixed to 0.5 in our experiments.
I am also preparing the script to work with resnet as well. It will be released soon.

**Comment by MarcelSimon** [comment]
If you use our ResNet 50 from https://github.com/cvjena/cnn-models/tree/master/ResNet_preact/ResNet50_cvgj  then you can append the following snipped after the last_relu layer instead of waiting for the script. However, please be aware that training from scratch is fairly difficult due to the L2 normalization and that successful training might require a lot of fiddling with the solver parameters or a removal of the L2 normalization layer.


```
layer {
  name: "alpha_power"
  type: "SignedPower"
  bottom: "layer_512_3_sum"
  top: "alpha_power"
  param {
    name: "alpha_power"
    lr_mult: 10
    decay_mult: 0
  }
  power_param {
    power: 1.0
  }
}
layer {
  name: "outer_product"
  type: "CompactBilinear"
  bottom: "layer_512_3_sum"
  bottom: "alpha_power"
  top: "outer_product"
  compact_bilinear_param {
    num_output: 8192
  }
}
layer {
  name: "root"
  type: "SignedPower"
  bottom: "outer_product"
  top: "root"
  param {
    lr_mult: 0
    decay_mult: 0
  }
  power_param {
    power: 0.5
  }
}
layer {
  name: "l2"
  type: "L2Normalize"
  bottom: "root"
  top: "l2"
}
layer {
  name: "fc8_ft"
  type: "InnerProduct"
  bottom: "l2"
  top: "fc8_ft"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 2
  }
  inner_product_param {
    num_output: 201
  }
}
layer {
  name: "loss"
  type: "SoftmaxWithLoss"
  bottom: "fc8_ft"
  bottom: "label"
  top: "loss"
}
layer {
  name: "Accuracy"
  type: "Accuracy"
  bottom: "fc8_ft"
  bottom: "label"
  top: "Accuracy"
  include {
    phase: TEST
  }
}

**Comment by hiyijian** [comment]
Thank you @MarcelSimon . I will try this and get back to you. No problem to finetune since I have a normal softmax loss caffemodel already. But I think the CompactBilinear should have two input ? The above snipped has only one

**Comment by MarcelSimon** [comment]
I'm not quite sure what you mean :) CompactBilinear has two different inputs in the snippet, please check again

```
  ...
layer {
  name: "outer_product"
  type: "CompactBilinear"
  bottom: "layer_512_3_sum"
  bottom: "alpha_power"
...

**Comment by hiyijian** [comment]
Cool. I am misleaded by network visual software "netscope". 
Ignore me :）

**Comment by MarcelSimon** [comment]
Yeah, it's missing in the netscope because the layer layer_512_3_sum is not defined in the snippet. No problem :)
