### ISSUE TITLE
code to calculate gradient of alpha

### ISSUE THREAD

**Issue by Eniac-Xie** [cvjena/alpha_pooling#2]
Hi, @MarcelSimon 

Thanks for sharing this code!

I am trying to find the code that calculate the gradient w.r.t. alpha, and I check the file caffe_pp2/src/caffe/layers/signed_power_layer.cpp
but can not find it, would you please show me which lines compute this? I only find the gradient w.r.t. bottom data.

Thank you!

**Comment by MarcelSimon** [comment]
Hi @Eniac-Xie 
The source only contains the GPU implementation, hence you can find the diff at https://github.com/cvjena/caffe_pp2/blob/0a7d6efea371a82117410b289a090132fbab6bbe/src/caffe/layers/signed_power_layer.cu#L126  The CPU implementation is from the power layer, which I used as a basis, and hence does not implement the layer correctly. Sorry for the confusion, I will add an error message to the CPU implementation until there is one.

**Comment by Eniac-Xie** [comment]
OK, thanks for your response!
